[package]
name = "watchmark-tauri"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "watchmark_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "unwind"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_System_Threading", "Win32_Storage_FileSystem", "Win32_Foundation"] }

[dependencies]
native-dialog = "0.7.0"
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.38.0", features = ["bundled"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream", "multipart"] }
reqwest-middleware = "0.3.3"
reqwest-retry = "0.6.1"
task-local-extensions = "0.1.4"
lazy_static = "1.4.0"
walkdir = "2.5.0"
regex = "1.12.3"
tokio = { version = "1.50.0", features = ["full"] }
directories = "6.0.0"
uuid = { version = "1.22.0", features = ["v4"] }
chrono = "0.4.44"
http = "1.4.0"
percent-encoding = "2.3.2"
thiserror = "2.0.18"
tauri-plugin-dialog = "2"
log = "0.4.29"
tauri-plugin-shell = "2.3.5"
tauri-plugin-notification = "2.3.3"
tauri-plugin-global-shortcut = "2.3.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
dunce = "1.0.5"
keyring = { version = "3.6.3", features = ["windows-native", "linux-native", "apple-native"] }
base64 = "0.22.1"
twox-hash = "2.1.2"
fs3 = "0.5.0"
tokio-util = "0.7.18"
image = "0.24.9"
tauri-plugin-fs = "2.4.5"
tauri-plugin-os = "2.3.2"
parselnk = "0.1.1"
strsim = "0.11.1"
rand = "0.8"
chrono-tz = "0.10.4"
iana-time-zone = "0.1.65"
